name: Auto-label issues and Merged PRs

on:
  pull_request:
    types: [closed]
  issues:
    types: [opened]

jobs:
  label-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Add labels to merged PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'gssoc-ext,hacktober-accepted'
          issue-number: ${{ github.event.pull_request.number }}

  label-new-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Add labels to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'gssoc-ext,hacktober-accepted'
          issue-number: ${{ github.event.issue.number }}
